### ISSUE TITLE
[BUG] E2E mortgage notebook breaks on Pascal and Rapids 0.6 & 0.7

### ISSUE THREAD

**Issue by alawami** [rapidsai/notebooks-extended#58]
Running the mortgage notebook:

https://github.com/rapidsai/notebooks-extended/blob/master/advanced/E2E/mortgage/mortgage_e2e.ipynb

On NGC containers:

0.7-cuda10.0-devel-ubuntu18.04-gcc7-py3.6
and
0.6-cuda10.0-devel-ubuntu18.04-gcc7-py3.6

On dual P6000 cards, it can only do 2 parts of the data. However, on Rapids 0.5.1 I can run up to 6 parts of the data.

I have not noticed this issue when I ran it on dual RTX8000.

Note, that I also have a P400 with the dual P6000. On Rapids 0.5.1, it will only detect the P6000s, but on Rapids 0.6 and Rapids 0.7 it would detect all three cards (This also result in workers dying and restarting during ETL).

**Comment by datametrician** [comment]
If you're using a container you disable the P400 card. This is causing the issue. Please use GPU isolation https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation-(version-1.0) and let us know if it solves the problem.

**Comment by alawami** [comment]
@datametrician Thank you. I've verified that this works for Rapids 0.7.

Even though it works, it does however give the following error in the terminal:

```
/data/acq/Acquisition_2015Q1.txt
/data/acq/Acquisition_2015Q2.txt
/data/perf/Performance_2015Q1.txt
/data/perf/Performance_2015Q2.txt
/data/acq/Acquisition_2015Q4.txt
/data/acq/Acquisition_2015Q3.txt
/data/perf/Performance_2015Q3.txt
/data/perf/Performance_2015Q4.txt
tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 104 memory: 4523 MB fds: 49>>
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_common.py", line 342, in wrapper
    ret = self._cache[fun]
KeyError: <function Process._parse_stat_file at 0x7fe18eea69d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_pslinux.py", line 1554, in _parse_stat_file
    data = f.read()
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.6/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/conda/envs/rapids/lib/python3.6/site-packages/distributed/system_monitor.py", line 48, in update
    cpu = self.proc.cpu_percent()
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/__init__.py", line 1111, in cpu_percent
    pt2 = self._proc.cpu_times()
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_pslinux.py", line 1507, in wrapper
    return fun(self, *args, **kwargs)
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_pslinux.py", line 1699, in cpu_times
    values = self._parse_stat_file()
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_pslinux.py", line 1507, in wrapper
    return fun(self, *args, **kwargs)
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_common.py", line 349, in wrapper
    ret = self._cache[fun] = fun(self)
  File "/conda/envs/rapids/lib/python3.6/site-packages/psutil/_pslinux.py", line 1554, in _parse_stat_file
    data = f.read()
OSError: [Errno 9] Bad file descriptor
/data/acq/Acquisition_2016Q2.txt
/data/perf/Performance_2016Q2.txt
/data/acq/Acquisition_2016Q1.txt
/data/perf/Performance_2016Q1.txt
```
